#!/bin/bash
set -euo pipefail

RIPPLED_DIR=/etc/config/
RIPPLED_CONF=${RIPPLED_DIR}/rippled.cfg
RIPPLED_VALIDATORS=${RIPPLED_DIR}/validators.txt
TESTNET=${TESTNET:-1}

if [ "${TESTNET}" == "0" ]; then
    RIPPLED_IPS="r.ripple.com 51235"
    RIPPLED_VALIDATORS_LIST="https://vl.ripple.com"
    RIPPLED_VALIDATORS_KEY="ED2677ABFFD1B33AC6FBC3062B71F1E8397C1505E1C42C64D11AD1B28FF73F4734"
else
    RIPPLED_IPS="r.altnet.rippletest.net 51235"
    RIPPLED_VALIDATORS_LIST="https://vl.altnet.rippletest.net"
    RIPPLED_VALIDATORS_KEY="ED264807102805220DA0F312E71FC2C69E1552C9C5790F6C25E3729DEB573D5860"
fi


#create config if not exists
if [ ! -e "${RIPPLED_CONF}" ]; then
      tee -a >${RIPPLED_CONF} <<EOF
[server]
port_rpc_admin_local
port_ws_public
#port_peer
# port_peer
# port_ws_admin_local
# ssl_key = /etc/ssl/private/server.key
# ssl_cert = /etc/ssl/certs/server.crt

[port_rpc_admin_local]
port = ${RPC_PORT:-5005}
ip = ${RPCALLOWIP:-0.0.0.0}
admin = 127.0.0.1
protocol = http

[port_ws_public]
port = 80
ip = 0.0.0.0
protocol = ws

[port_peer]
port = 51235
ip = 0.0.0.0
protocol = peer

# [port_ws_admin_local]
# port = 6006
# ip = 127.0.0.1
# admin = 127.0.0.1
# protocol = ws

[node_size]
small

# tiny
# small
# medium
# large
# huge

[node_db]
type=NuDB
path=/var/lib/rippled/db/nudb
advisory_delete=0

# How many ledgers do we want to keep (history)?
# Integer value that defines the number of ledgers
# between online deletion events
online_delete=256

[ledger_history]
# How many ledgers do we want to keep (history)?
# Integer value (ledger count)
# or (if you have lots of TB SSD storage): 'full'
256

[database_path]
/var/lib/rippled/db

[debug_logfile]
/var/log/rippled/debug.log

[sntp_servers]
time.windows.com
time.apple.com
time.nist.gov
pool.ntp.org

[ips]
${RIPPLED_IPS}

[validators_file]
validators.txt

[rpc_startup]
{ "command": "log_level", "severity": "info" }

# severity (order: lots of information .. only errors)
# debug
# info
# warn
# error
# fatal

[ssl_verify]
1      

#enable remote signing
[signing_support]
${SIGNSUPPORT:-true}
EOF
fi

#create validator if not exists
if [ ! -e "${RIPPLED_VALIDATORS}" ]; then
      tee -a >${RIPPLED_VALIDATORS} <<EOF
[validator_list_sites]
${RIPPLED_VALIDATORS_LIST}

[validator_list_keys]
${RIPPLED_VALIDATORS_KEY}   
EOF
fi

# Start rippled, Passthrough other arguments
exec /opt/ripple/bin/rippled --conf ${RIPPLED_CONF} "$@"